name:  trigger Name
# Trigger this workflow on pushes to the specified branch
on:
  push:
    branches:
      - master # Replace with your branch name
jobs:
  deploy:
    runs-on: ubuntu-latest # Run this job on the latest Ubuntu version

    steps:
      - name: Checkout
        uses: actions/checkout@v2 # Check out your repository code

      - name: SSH and run commands
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # Reference the private key stored in GitHub Secrets
        run: |
          echo "$PRIVATE_KEY" > private_key.pem # Write the private key to a file
          chmod 600 private_key.pem # Set the appropriate permissions for the key file

          # Establish an SSH connection and execute commands on the remote server
          ssh -o StrictHostKeyChecking=no -i private_key.pem jony@pdb.net.pl <<EOF
            # Your server commands go here. Replace these commands with those relevant to your project.

            cd  /var/www/kkm
            source ../venv/bin/activate
            git checkout master
            git pull
            pip3 install .
            # python3 manage.py makemigrations
            # python3 migrate
            sudo systemctl restart kkm_production.service
            # cd /home/azureuser/github/canopus-platform
            # export NODE_OPTIONS=--max-old-space-size=4096
            # cd /home/azureuser/github/canopus-platform
            # git checkout main
            # git pull
            # git log --oneline -10
            # # Add other commands if needed
            # npm run test
            # sudo service apache2 restart
          EOF

          rm -f private_key.pem # Remove the private key file after use for security
    permissions:
      contents: read
      actions: write
      id-token: write
